apiVersion: apps/v1
kind: Deployment
metadata:
  name: "qr-frontend-admin-dev"
  namespace: "application-dev"
  labels:
    application: "frontend"
    stage: "dev"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  selector:
    matchLabels:
      application: "frontend-admin"
      stage: "dev"
  template:
    metadata:
      labels:
        application: "frontend-admin"
        stage: "dev"
    spec:
      restartPolicy: Always
      containers:
        - name: frontend-dev
          image: hakobmkoyan771/frontend-qr:0.1.0-rc2
          imagePullPolicy: IfNotPresent
          ports:
            - name: front-adm-port
              containerPort: 3000
              protocol: "TCP"
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: "API_URL"
                  name: "backend-app-dev-cm"
